defaults: &defaults  
  host: <%= ENV['MONGOHQ_HOST'] %>
  port: <%= ENV['MONGOHQ_PORT'] %>
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  database: <%= ENV['MONGOHQ_DATABASE'] %>
  autocreate_indexes: true


development:  
  host: localhost
  database: checkinn_development
  autocreate_indexes: true


test:  
  host: localhost
  database: checkinn_test
  autocreate_indexes: true

production:  
    <<: *defaults