defaults: &defaults  
    host: <%= ENV['MONGOHQ_URL'] %>
    port: <%= ENV['MONGOHQ_PORT'] %>
    username: <%= ENV['MONGOHQ_USER'] %>
    password: <%= ENV['MONGOHQ_PASS'] %>
    database: <%= ENV['MONGOHQ_DATABASE'] %>
    autocreate_indexes: true


development:  
  host: localhost
  database: checkinn_development
  autocreate_indexes: true


test:  
  host: localhost
  database: checkinn_test
  autocreate_indexes: true

production:  
    <<: *defaults